"""
Flask + Three.js based 3D mesh viewer with per-face color editing.
"""
import threading
import webbrowser
from pathlib import Path

import numpy as np
from flask import Flask, jsonify, request

from editor.color_editor import ColorEditor

app = Flask(__name__)

# --- global state ---
_state = {
    'editor': None,
    'output_path': None,
    'history': [],
}


def parse_colored_obj(obj_path: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Parse OBJ + MTL files generated by save_colored_obj.

    Args:
        obj_path: path to .obj file

    Returns:
        vertices: (V, 3)
        faces: (F, 3)
        face_colors: (F, 3) RGB in [0, 1]
    """
    obj_path = Path(obj_path)
    mtl_path = obj_path.with_suffix('.mtl')

    materials = {}
    if mtl_path.exists():
        current_mtl = None
        with open(mtl_path) as f:
            for line in f:
                line = line.strip()
                if line.startswith('newmtl '):
                    current_mtl = line.split()[1]
                elif line.startswith('Kd ') and current_mtl:
                    parts = line.split()
                    materials[current_mtl] = [float(parts[1]), float(parts[2]), float(parts[3])]

    vertices = []
    faces = []
    face_colors = []
    current_color = [0.8, 0.8, 0.8]

    with open(obj_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith('v '):
                parts = line.split()
                vertices.append([float(p) for p in parts[1:4]])
            elif line.startswith('usemtl '):
                current_color = materials.get(line.split()[1], [0.8, 0.8, 0.8])
            elif line.startswith('f '):
                parts = line.split()
                face = [int(p.split('/')[0]) - 1 for p in parts[1:4]]
                faces.append(face)
                face_colors.append(current_color[:])

    return (
        np.array(vertices, dtype=np.float32),
        np.array(faces, dtype=np.int32),
        np.array(face_colors, dtype=np.float32),
    )


@app.route('/')
def index():
    return HTML_TEMPLATE, 200, {'Content-Type': 'text/html; charset=utf-8'}


@app.route('/api/mesh')
def get_mesh():
    editor = _state['editor']
    verts = editor.vertices
    faces = editor.faces
    colors = editor.face_colors

    positions = verts[faces].reshape(-1, 3)
    vertex_colors = np.repeat(colors, 3, axis=0)

    return jsonify({
        'positions': positions.flatten().tolist(),
        'colors': vertex_colors.flatten().tolist(),
        'face_count': int(len(faces)),
    })


@app.route('/api/color', methods=['POST'])
def apply_color():
    data = request.json
    face_indices = data['face_indices']
    rgb = data['rgb']

    editor = _state['editor']
    _state['history'].append(
        (list(face_indices), editor.face_colors[face_indices].copy())
    )

    editor.set_rgb(face_indices, tuple(rgb))
    return jsonify({'status': 'ok'})


@app.route('/api/adjust', methods=['POST'])
def adjust():
    """Apply HSV adjustment to selected faces."""
    data = request.json
    face_indices = data['face_indices']
    kind = data['kind']   # 'hue' | 'brightness' | 'saturation'
    value = float(data['value'])

    editor = _state['editor']
    _state['history'].append(
        (list(face_indices), editor.face_colors[face_indices].copy())
    )

    if kind == 'hue':
        editor.shift_hue(face_indices, value)
    elif kind == 'brightness':
        editor.adjust_brightness(face_indices, value)
    elif kind == 'saturation':
        editor.adjust_saturation(face_indices, value)

    vertex_colors = np.repeat(editor.face_colors, 3, axis=0)
    return jsonify({'colors': vertex_colors.flatten().tolist()})


@app.route('/api/undo', methods=['POST'])
def undo():
    if not _state['history']:
        return jsonify({'status': 'nothing to undo'})

    editor = _state['editor']
    face_ids, prev_colors = _state['history'].pop()
    editor.face_colors[face_ids] = prev_colors

    vertex_colors = np.repeat(editor.face_colors, 3, axis=0)
    return jsonify({'colors': vertex_colors.flatten().tolist()})


@app.route('/api/save', methods=['POST'])
def save():
    editor = _state['editor']
    output_path = _state['output_path']
    editor.save(output_path)
    print(f"Saved -> {output_path}")
    return jsonify({'status': 'saved', 'path': str(output_path)})


HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>ModelPainter</title>
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { background:#0d1117; color:#c9d1d9; font-family:'Segoe UI',system-ui,sans-serif; display:flex; height:100vh; overflow:hidden; }
#sidebar { width:230px; min-width:230px; background:#161b22; border-right:1px solid #30363d; padding:14px; display:flex; flex-direction:column; gap:10px; overflow-y:auto; }
#canvas-container { flex:1; position:relative; }
h1 { font-size:15px; font-weight:600; color:#58a6ff; padding-bottom:10px; border-bottom:1px solid #30363d; }
.section { display:flex; flex-direction:column; gap:6px; }
.label { font-size:10px; color:#8b949e; text-transform:uppercase; letter-spacing:0.5px; font-weight:600; }
.divider { border-top:1px solid #30363d; margin:2px 0; }
input[type=color] { width:100%; height:32px; border:1px solid #30363d; border-radius:5px; cursor:pointer; background:none; padding:2px; }
.rgb-row { display:flex; gap:4px; }
.rgb-col { flex:1; display:flex; flex-direction:column; gap:2px; text-align:center; }
.rgb-col input { width:100%; padding:4px 2px; background:#0d1117; border:1px solid #30363d; border-radius:4px; color:#c9d1d9; font-size:12px; text-align:center; outline:none; }
.rgb-col input:focus { border-color:#58a6ff; }
.rgb-col span { font-size:10px; color:#8b949e; }
.slider-row { display:flex; align-items:center; gap:6px; }
.slider-label { font-size:11px; color:#8b949e; width:36px; flex-shrink:0; }
.slider-row input[type=range] { flex:1; height:4px; accent-color:#e3912d; cursor:pointer; }
.slider-val { font-size:11px; color:#c9d1d9; width:34px; text-align:right; flex-shrink:0; font-variant-numeric:tabular-nums; }
.btn { width:100%; padding:7px; border:none; border-radius:5px; cursor:pointer; font-size:12px; font-weight:500; transition:filter .15s; }
.btn:hover { filter:brightness(1.15); }
.btn-apply { background:#238636; color:#fff; }
.btn-adj { background:#e3912d; color:#fff; }
.btn-sub { background:#21262d; color:#c9d1d9; border:1px solid #30363d; }
.btn-save { background:#1f6feb; color:#fff; }
.btn-row { display:flex; gap:4px; }
.btn-row .btn { flex:1; }
.info { font-size:12px; color:#8b949e; line-height:2; margin-top:auto; }
.info span { color:#c9d1d9; }
#statusBar { position:absolute; bottom:12px; left:12px; background:rgba(22,27,34,0.92); border:1px solid #30363d; padding:5px 12px; border-radius:5px; font-size:11px; color:#8b949e; pointer-events:none; }
</style>
</head>
<body>
<div id="sidebar">
  <h1>ModelPainter</h1>

  <div class="section">
    <div class="label">Color</div>
    <input type="color" id="colorPicker" value="#ff0000">
    <div class="rgb-row">
      <div class="rgb-col"><input type="number" id="inR" min="0" max="255" value="255"><span>R</span></div>
      <div class="rgb-col"><input type="number" id="inG" min="0" max="255" value="0"><span>G</span></div>
      <div class="rgb-col"><input type="number" id="inB" min="0" max="255" value="0"><span>B</span></div>
    </div>
    <button class="btn btn-apply" onclick="applyColor()">Apply Color</button>
  </div>

  <div class="divider"></div>

  <div class="section">
    <div class="label">Adjust</div>
    <div class="slider-row">
      <span class="slider-label">Hue</span>
      <input type="range" id="slHue" min="-180" max="180" value="0" step="1"
             oninput="document.getElementById('valHue').textContent=this.value">
      <span class="slider-val" id="valHue">0</span>
    </div>
    <div class="slider-row">
      <span class="slider-label">Bright</span>
      <input type="range" id="slBright" min="0.1" max="3.0" value="1.0" step="0.05"
             oninput="document.getElementById('valBright').textContent=(+this.value).toFixed(2)">
      <span class="slider-val" id="valBright">1.00</span>
    </div>
    <div class="slider-row">
      <span class="slider-label">Sat</span>
      <input type="range" id="slSat" min="0.0" max="3.0" value="1.0" step="0.05"
             oninput="document.getElementById('valSat').textContent=(+this.value).toFixed(2)">
      <span class="slider-val" id="valSat">1.00</span>
    </div>
    <div class="btn-row">
      <button class="btn btn-adj" onclick="applyAdjust('hue')">Hue</button>
      <button class="btn btn-adj" onclick="applyAdjust('brightness')">Bright</button>
      <button class="btn btn-adj" onclick="applyAdjust('saturation')">Sat</button>
    </div>
  </div>

  <div class="divider"></div>

  <div class="section">
    <div class="label">Selection</div>
    <div class="btn-row">
      <button class="btn btn-sub" onclick="selectAll()">Select All</button>
      <button class="btn btn-sub" onclick="clearSelection()">Clear</button>
    </div>
    <button class="btn btn-sub" onclick="undo()">Undo</button>
  </div>

  <div class="divider"></div>

  <button class="btn btn-save" onclick="save()">Save</button>

  <div class="info">
    Selected: <span id="selCount">0</span> faces<br>
    Total: <span id="totalCount">-</span> faces
  </div>
</div>

<div id="canvas-container"></div>
<div id="statusBar">Loading mesh...</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script>
(function () {
    const container = document.getElementById('canvas-container');
    const statusBar = document.getElementById('statusBar');
    const selCountEl = document.getElementById('selCount');
    const totalCountEl = document.getElementById('totalCount');

    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(container.clientWidth, container.clientHeight);
    container.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x0d1117);
    scene.add(new THREE.AmbientLight(0xffffff, 0.6));
    const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);
    dirLight.position.set(2, 3, 4);
    scene.add(dirLight);
    scene.add(new THREE.AxesHelper(0.5));

    const camera = new THREE.PerspectiveCamera(60, container.clientWidth / container.clientHeight, 0.001, 1000);

    let isDragging = false;
    let mouseDownPos = { x: 0, y: 0 };
    let prevMouse = { x: 0, y: 0 };
    let sph = { theta: 0, phi: Math.PI / 2.5, r: 5 };
    const orbitTarget = new THREE.Vector3();

    function updateCamera() {
        const sx = Math.sin(sph.phi), cx = Math.cos(sph.phi);
        const sy = Math.sin(sph.theta), cy = Math.cos(sph.theta);
        camera.position.set(orbitTarget.x + sph.r * sx * sy, orbitTarget.y + sph.r * cx, orbitTarget.z + sph.r * sx * cy);
        camera.lookAt(orbitTarget);
    }
    updateCamera();

    const el = renderer.domElement;
    el.addEventListener('mousedown', e => { isDragging = true; mouseDownPos = { x: e.clientX, y: e.clientY }; prevMouse = { x: e.clientX, y: e.clientY }; });
    el.addEventListener('mousemove', e => { if (!isDragging) return; sph.theta -= (e.clientX - prevMouse.x) * 0.008; sph.phi = Math.max(0.05, Math.min(Math.PI - 0.05, sph.phi - (e.clientY - prevMouse.y) * 0.008)); prevMouse = { x: e.clientX, y: e.clientY }; updateCamera(); });
    el.addEventListener('mouseup', () => { isDragging = false; });
    el.addEventListener('mouseleave', () => { isDragging = false; });
    el.addEventListener('wheel', e => { sph.r = Math.max(0.01, sph.r * (1 + e.deltaY * 0.001)); updateCamera(); });

    const raycaster = new THREE.Raycaster();
    const mouseVec = new THREE.Vector2();

    let meshObj = null, colorAttr = null;
    const currentColors = [];
    const selectedFaces = new Set();
    const HIGHLIGHT = [1.0, 0.9, 0.0];

    function setFaceColor(fi, rgb) {
        const base = fi * 9;
        for (let v = 0; v < 3; v++) {
            colorAttr.array[base + v * 3]     = rgb[0];
            colorAttr.array[base + v * 3 + 1] = rgb[1];
            colorAttr.array[base + v * 3 + 2] = rgb[2];
        }
    }

    function applyRemoteColors(colArr) {
        colorAttr.array.set(colArr);
        for (let i = 0; i < currentColors.length; i++) {
            const b = i * 9;
            currentColors[i] = [colArr[b], colArr[b + 1], colArr[b + 2]];
        }
        selectedFaces.clear();
        colorAttr.needsUpdate = true;
        selCountEl.textContent = 0;
    }

    function toggleFace(fi, shift) {
        if (!shift) { selectedFaces.forEach(f => setFaceColor(f, currentColors[f])); selectedFaces.clear(); }
        if (selectedFaces.has(fi)) { setFaceColor(fi, currentColors[fi]); selectedFaces.delete(fi); }
        else { selectedFaces.add(fi); setFaceColor(fi, HIGHLIGHT); }
        colorAttr.needsUpdate = true;
        selCountEl.textContent = selectedFaces.size;
    }

    el.addEventListener('click', e => {
        const dx = e.clientX - mouseDownPos.x, dy = e.clientY - mouseDownPos.y;
        if (dx * dx + dy * dy > 25 || !meshObj) return;
        const rect = el.getBoundingClientRect();
        mouseVec.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
        mouseVec.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
        raycaster.setFromCamera(mouseVec, camera);
        const hits = raycaster.intersectObject(meshObj);
        if (hits.length > 0) toggleFace(hits[0].faceIndex, e.shiftKey);
    });

    fetch('/api/mesh').then(r => r.json()).then(data => {
        const F = data.face_count;
        const posArr = new Float32Array(data.positions);
        const colArr = new Float32Array(data.colors);
        for (let i = 0; i < F; i++) { const b = i * 9; currentColors.push([colArr[b], colArr[b + 1], colArr[b + 2]]); }
        const geo = new THREE.BufferGeometry();
        geo.setAttribute('position', new THREE.BufferAttribute(posArr, 3));
        geo.setAttribute('color', new THREE.BufferAttribute(colArr.slice(), 3));
        geo.computeVertexNormals();
        colorAttr = geo.attributes.color;
        const mat = new THREE.MeshPhongMaterial({ vertexColors: true, side: THREE.DoubleSide });
        meshObj = new THREE.Mesh(geo, mat);
        scene.add(meshObj);
        const box = new THREE.Box3().setFromObject(meshObj);
        box.getCenter(orbitTarget);
        sph.r = box.getSize(new THREE.Vector3()).length() * 1.5;
        updateCamera();
        totalCountEl.textContent = F;
        statusBar.textContent = 'Loaded ' + F + ' faces.';
    }).catch(e => { statusBar.textContent = 'Error: ' + e.message; });

    // color picker <-> RGB sync
    document.getElementById('colorPicker').addEventListener('input', e => {
        const h = e.target.value;
        document.getElementById('inR').value = parseInt(h.slice(1, 3), 16);
        document.getElementById('inG').value = parseInt(h.slice(3, 5), 16);
        document.getElementById('inB').value = parseInt(h.slice(5, 7), 16);
    });
    function toHex(v) { return Math.max(0, Math.min(255, v | 0)).toString(16).padStart(2, '0'); }
    ['inR', 'inG', 'inB'].forEach(id => {
        document.getElementById(id).addEventListener('input', () => {
            const r = +document.getElementById('inR').value || 0;
            const g = +document.getElementById('inG').value || 0;
            const b = +document.getElementById('inB').value || 0;
            document.getElementById('colorPicker').value = '#' + toHex(r) + toHex(g) + toHex(b);
        });
    });

    window.applyColor = function () {
        if (!selectedFaces.size) { statusBar.textContent = 'No faces selected.'; return; }
        const r = +document.getElementById('inR').value || 0;
        const g = +document.getElementById('inG').value || 0;
        const b = +document.getElementById('inB').value || 0;
        const rgb = [r / 255, g / 255, b / 255];
        const faceList = Array.from(selectedFaces);
        fetch('/api/color', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ face_indices: faceList, rgb })
        }).then(() => {
            faceList.forEach(fi => { currentColors[fi] = rgb.slice(); setFaceColor(fi, rgb); });
            selectedFaces.clear();
            colorAttr.needsUpdate = true;
            selCountEl.textContent = 0;
            statusBar.textContent = 'Applied to ' + faceList.length + ' faces.';
        });
    };

    window.applyAdjust = function (kind) {
        if (!selectedFaces.size) { statusBar.textContent = 'No faces selected.'; return; }
        const sliderIds = { hue: 'slHue', brightness: 'slBright', saturation: 'slSat' };
        const value = parseFloat(document.getElementById(sliderIds[kind]).value);
        const faceList = Array.from(selectedFaces);
        fetch('/api/adjust', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ face_indices: faceList, kind, value })
        }).then(r => r.json()).then(data => {
            applyRemoteColors(new Float32Array(data.colors));
            statusBar.textContent = kind + ' adjusted on ' + faceList.length + ' faces.';
        });
    };

    window.selectAll = function () {
        if (!meshObj) return;
        const F = currentColors.length;
        selectedFaces.clear();
        for (let i = 0; i < F; i++) { selectedFaces.add(i); setFaceColor(i, HIGHLIGHT); }
        colorAttr.needsUpdate = true;
        selCountEl.textContent = F;
        statusBar.textContent = 'All ' + F + ' faces selected.';
    };

    window.clearSelection = function () {
        selectedFaces.forEach(fi => setFaceColor(fi, currentColors[fi]));
        selectedFaces.clear();
        if (colorAttr) colorAttr.needsUpdate = true;
        selCountEl.textContent = 0;
        statusBar.textContent = 'Selection cleared.';
    };

    window.undo = function () {
        fetch('/api/undo', { method: 'POST' }).then(r => r.json()).then(data => {
            if (data.colors) {
                applyRemoteColors(new Float32Array(data.colors));
                statusBar.textContent = 'Undo done.';
            } else {
                statusBar.textContent = data.status || 'Nothing to undo.';
            }
        });
    };

    window.save = function () {
        fetch('/api/save', { method: 'POST' }).then(r => r.json()).then(data => {
            statusBar.textContent = 'Saved to ' + data.path;
        });
    };

    function animate() { requestAnimationFrame(animate); renderer.render(scene, camera); }
    animate();

    window.addEventListener('resize', () => {
        camera.aspect = container.clientWidth / container.clientHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(container.clientWidth, container.clientHeight);
    });
})();
</script>
</body>
</html>"""


def launch_viewer(obj_path: str, output_path: str = None, port: int = 5000):
    """
    Launch Flask-based 3D color editor in browser.

    Args:
        obj_path: path to colored .obj file
        output_path: path to save edited mesh
        port: local server port
    """
    if output_path is None:
        stem = Path(obj_path).stem
        output_path = str(Path(obj_path).parent / (stem + '_edited.obj'))

    print(f"Loading mesh from {obj_path} ...")
    vertices, faces, face_colors = parse_colored_obj(obj_path)
    print(f"Loaded: {len(vertices)} vertices, {len(faces)} faces")

    _state['editor'] = ColorEditor(vertices, faces, face_colors)
    _state['output_path'] = output_path
    _state['history'] = []

    def _open():
        import time
        time.sleep(1.5)
        webbrowser.open(f'http://localhost:{port}')

    threading.Thread(target=_open, daemon=True).start()

    print(f"\nModelPainter running at http://localhost:{port}")
    print("Press Ctrl+C to quit.\n")

    app.run(port=port, debug=False, use_reloader=False)


if __name__ == '__main__':
    launch_viewer(
        obj_path='./output/mesh/mesh_colored.obj',
        output_path='./output/mesh/mesh_edited.obj',
    )
